### ISSUE TITLE
Which maven repo is used for hosting released library

### ISSUE THREAD

**Issue by emartynov** [vokal/Android-Lint-Checks#12]
I put lines as described in `README` to my `build.gradle`:

```
  compile 'io.vokal.lint:rxlifecycle:1.0.3'
  compile 'io.vokal.lint:todo:1.0.3'
```

But I'm getting now error `Could not find 'io.vokal.lint:rxlifecycle:1.0.3'`

**Comment by nick-fedesna** [comment]
Sorry about that, it looks like `1.0.3` never got pushed to Bintray (JCenter).  
For the time being you can use version `1.0.2` if you want until we get that pushed:
https://bintray.com/vokal/vokal-oss/io.vokal.lint:rxlifecycle

**Comment by aphexcx** [comment]
Yo, you should really push 1.0.3 out to jcenter!

**Comment by scottferg** [comment]
Yeah yo

**Comment by nick-fedesna** [comment]
`1.0.3` pushed
